# NUMPY

In [18]:
import numpy as np


In [19]:
names = ['lasith', 'vidu', 'pusse', 'vihanga']


In [20]:
x = np.array(names)

In [21]:
type(names)

list

In [22]:
np.shape(names)

(4,)

In [23]:
x.shape

(4,)

In [24]:
np.array([2,3,4,5])

array([2, 3, 4, 5])

In [25]:
np.array((1,2,3))

array([1, 2, 3])

In [26]:
np.array({1,2,3,4}).shape

()

In [27]:
arr2d = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [30]:
arr2d


array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [31]:
arr2d.shape

(3, 3)

In [32]:
x


array(['lasith', 'vidu', 'pusse', 'vihanga'], dtype='<U7')

In [34]:
x = np.array({1,2,3})

In [35]:
x


array({1, 2, 3}, dtype=object)

In [36]:
x = np.array ((1,2,3))

In [37]:
x


array([1, 2, 3])

In [38]:
np.longdouble(1/3
              )

0.3333333333333333